#include "KeyStringMapping.hpp"

//instantiate the maps as a static variables
std::map<std::string, sf::Keyboard::Key> KeyStringMapping::keyStringMap {
	{"Unknown" , sf::Keyboard::Unknown},
	{"A" , sf::Keyboard::A},
	{"B" , sf::Keyboard::B},
	{"C" , sf::Keyboard::C},
	{"D" , sf::Keyboard::D},
	{"E" , sf::Keyboard::E},
	{"F" , sf::Keyboard::F},
	{"G" , sf::Keyboard::G},
	{"H" , sf::Keyboard::H},
	{"I" , sf::Keyboard::I},
	{"J" , sf::Keyboard::J},
	{"K" , sf::Keyboard::K},
	{"L" , sf::Keyboard::L},
	{"M" , sf::Keyboard::M},
	{"N" , sf::Keyboard::N},
	{"O" , sf::Keyboard::O},
	{"P" , sf::Keyboard::P},
	{"Q" , sf::Keyboard::Q},
	{"R" , sf::Keyboard::R},
	{"S" , sf::Keyboard::S},
	{"T" , sf::Keyboard::T},
	{"U" , sf::Keyboard::U},
	{"V" , sf::Keyboard::V},
	{"W" , sf::Keyboard::W},
	{"X" , sf::Keyboard::X},
	{"Y" , sf::Keyboard::Y},
	{"Z" , sf::Keyboard::Z},
	{"Num0" , sf::Keyboard::Num0},
	{"Num1" , sf::Keyboard::Num1},
	{"Num2" , sf::Keyboard::Num2},
	{"Num3" , sf::Keyboard::Num3},
	{"Num4" , sf::Keyboard::Num4},
	{"Num5" , sf::Keyboard::Num5},
	{"Num6" , sf::Keyboard::Num6},
	{"Num7" , sf::Keyboard::Num7},
	{"Num8" , sf::Keyboard::Num8},
	{"LControl" , sf::Keyboard::LControl},
	{"LShift" , sf::Keyboard::LShift},
	{"LAlt" , sf::Keyboard::LAlt},
	{"LSystem" , sf::Keyboard::LSystem},
	{"RControl" , sf::Keyboard::RControl},
	{"RShift" , sf::Keyboard::RShift},
	{"RAlt" , sf::Keyboard::RAlt},
	{"RSystem" , sf::Keyboard::RSystem},
	{"Menu" , sf::Keyboard::Menu},
	{"LBracket" , sf::Keyboard::LBracket},
	{"RBracket" , sf::Keyboard::RBracket},
	{"Semicolon" , sf::Keyboard::Semicolon},
	{"Comma" , sf::Keyboard::Comma},
	{"Period" , sf::Keyboard::Period},
	{"Quote" , sf::Keyboard::Quote},
	{"/" , sf::Keyboard::Slash},
	{"\\" , sf::Keyboard::Backslash},
	{"~" , sf::Keyboard::Tilde},
	{"=" , sf::Keyboard::Equal},
	{"-" , sf::Keyboard::Hyphen},
	{"Space" , sf::Keyboard::Space},
	{"Enter" , sf::Keyboard::Enter},
	{"Backspace" , sf::Keyboard::Backspace},
	{"Tab" , sf::Keyboard::Tab},
	{"PageUp" , sf::Keyboard::PageUp},
	{"PageDown" , sf::Keyboard::PageDown},
	{"End" , sf::Keyboard::End},
	{"Home" , sf::Keyboard::Home},
	{"Insert" , sf::Keyboard::Insert},
	{"Delete" , sf::Keyboard::Delete},
	{"Add" , sf::Keyboard::Add},
	{"Subtract" , sf::Keyboard::Subtract},
	{"Multiply" , sf::Keyboard::Multiply},
	{"Divide" , sf::Keyboard::Divide},
	{"LeftArrow" , sf::Keyboard::Left},
	{"RightArrow" , sf::Keyboard::Right},
	{"UpArrow" , sf::Keyboard::Up},
	{"DownArrow", sf::Keyboard::Down},
	{"Numpad0" , sf::Keyboard::Numpad0},
	{"Numpad1" , sf::Keyboard::Numpad1},
	{"Numpad2" , sf::Keyboard::Numpad2},
	{"Numpad3" , sf::Keyboard::Numpad3},
	{"Numpad4" , sf::Keyboard::Numpad4},
	{"Numpad5" , sf::Keyboard::Numpad5},
	{"Numpad6" , sf::Keyboard::Numpad6},
	{"Numpad7" , sf::Keyboard::Numpad7},
	{"Numpad8" , sf::Keyboard::Numpad8},
	{"Numpad9" , sf::Keyboard::Numpad9}
	};

std::map<sf::Keyboard::Key, std::string> KeyStringMapping::stringKeyMap {
	{sf::Keyboard::Unknown, "Unknown"},
	{sf::Keyboard::A, "A"},
	{sf::Keyboard::B, "B"},
	{sf::Keyboard::C, "C"},
	{sf::Keyboard::D, "D"},
	{sf::Keyboard::E, "E"},
	{sf::Keyboard::F, "F"},
	{sf::Keyboard::G, "G"},
	{sf::Keyboard::H, "H"},
	{sf::Keyboard::I, "I"},
	{sf::Keyboard::J, "J"},
	{sf::Keyboard::K, "K"},
	{sf::Keyboard::L, "L"},
	{sf::Keyboard::M, "M"},
	{sf::Keyboard::N, "N"},
	{sf::Keyboard::O, "O"},
	{sf::Keyboard::P, "P"},
	{sf::Keyboard::Q, "Q"},
	{sf::Keyboard::R, "R"},
	{sf::Keyboard::S, "S"},
	{sf::Keyboard::T, "T"},
	{sf::Keyboard::U, "U"},
	{sf::Keyboard::V, "V"},
	{sf::Keyboard::W, "W"},
	{sf::Keyboard::X, "X"},
	{sf::Keyboard::Y, "Y"},
	{sf::Keyboard::Z, "Z"},
	{sf::Keyboard::Num0, "Num0"},
	{sf::Keyboard::Num1, "Num1"},
	{sf::Keyboard::Num2, "Num2"},
	{sf::Keyboard::Num3, "Num3"},
	{sf::Keyboard::Num4, "Num4"},
	{sf::Keyboard::Num5, "Num5"},
	{sf::Keyboard::Num6, "Num6"},
	{sf::Keyboard::Num7, "Num7"},
	{sf::Keyboard::Num8, "Num8"},
	{sf::Keyboard::LControl, "LControl"},
	{sf::Keyboard::LShift, "LShift"},
	{sf::Keyboard::LAlt, "LAlt"},
	{sf::Keyboard::LSystem, "LSystem"},
	{sf::Keyboard::RControl, "RControl"},
	{sf::Keyboard::RShift, "RShift"},
	{sf::Keyboard::RAlt, "RAlt"},
	{sf::Keyboard::RSystem, "RSystem"},
	{sf::Keyboard::Menu, "Menu"},
	{sf::Keyboard::LBracket, "LBracket"},
	{sf::Keyboard::RBracket, "RBracket"},
	{sf::Keyboard::Semicolon, "Semicolon"},
	{sf::Keyboard::Comma, "Comma"},
	{sf::Keyboard::Period, "Period"},
	{sf::Keyboard::Quote, "Quote"},
	{sf::Keyboard::Slash, "/"},
	{sf::Keyboard::Backslash, "\\"},
	{sf::Keyboard::Tilde, "~"},
	{sf::Keyboard::Equal, "="},
	{sf::Keyboard::Hyphen, "-"},
	{sf::Keyboard::Space, "Space"},
	{sf::Keyboard::Enter, "Enter"},
	{sf::Keyboard::Backspace, "Backspace"},
	{sf::Keyboard::Tab, "Tab"},
	{sf::Keyboard::PageUp, "PageUp"},
	{sf::Keyboard::PageDown, "PageDown"},
	{sf::Keyboard::End, "End"},
	{sf::Keyboard::Home, "Home"},
	{sf::Keyboard::Insert, "Insert"},
	{sf::Keyboard::Delete, "Delete"},
	{sf::Keyboard::Add, "Add"},
	{sf::Keyboard::Subtract, "Subtract"},
	{sf::Keyboard::Multiply, "Multiply"},
	{sf::Keyboard::Divide, "Divide"},
	{sf::Keyboard::Left, "LeftArrow"},
	{sf::Keyboard::Right, "RightArrow"},
	{sf::Keyboard::Up, "UpArrow"},
	{sf::Keyboard::Down, "DownArrow"},
	{sf::Keyboard::Numpad0, "Numpad0"},
	{sf::Keyboard::Numpad1, "Numpad1"},
	{sf::Keyboard::Numpad2, "Numpad2"},
	{sf::Keyboard::Numpad3, "Numpad3"},
	{sf::Keyboard::Numpad4, "Numpad4"},
	{sf::Keyboard::Numpad5, "Numpad5"},
	{sf::Keyboard::Numpad6, "Numpad6"},
	{sf::Keyboard::Numpad7, "Numpad7"},
	{sf::Keyboard::Numpad8, "Numpad8"},
	{sf::Keyboard::Numpad9, "Numpad9"}
	};

//dummy constructor
KeyStringMapping::KeyStringMapping(){}

//convert the string to a key
sf::Keyboard::Key KeyStringMapping::stringToKey(std::string str){
	return keyStringMap[str];
}

//convert the key to a string
std::string KeyStringMapping::keyToString(sf::Keyboard::Key k){
	return stringKeyMap[k];
}
